#!bin/bash

#case syntax

# case $c=var  in 
# opt1)commands 1 ;;
# opt2) commands 2 ;;
#esac

ACTION=$1
 case $ACTION in 
 start)
 echo "starting the case";;
 stop)
 echo "stopping the case";;
 restart)
 echo "restarting the case";;
 *)
 eco "enter valid "
 esac
