#!bin/bash
<<comment
DATE="$(date +%F)"
echo $DATE;
#in order to pass a command , use parenthesis , since data, who are command line commands, here parenthesis are used
echo -e "\e[35mtotal number of active sessions: "$(who| wc -l)"\e[0m"
comment
echo $?