- name: Installing pwgen
  hosts: all
  become: True
  tasks:
    - name: Installing pwgen
      ansible.builtin.package:
        name: pwgen
        state: present
    - name: register variable
      ansible.builtn.shell: pwgen -N1 -s 20
      register: pwd
    -name: printing the password
     ansible.builtin.debug:
        msg: "{{pwd}}"
       