- name: Installing pwgen
  hosts: all
  become: True
  tasks:
    - name: register variable
      ansible.builtn.shell: pwgen -N 1 -s 20
      register: pwd
    - name: printing the password
      ansible.builtin.debug:
        msg: "{{pwd}}"
       