- name: demo on varibales(vars)
  hosts: all
  vars:
   PVS: Its a varibale
   list:
    - item1
    - item2
    - item3
    - item4
  Dictionary:
    num1: "1"
    num2: "2"
    num3: "3"
  tasks:
    - name: printing the varibale in upper
      ansible.builtin.debug:
        msg: "{{PVS | upper}}"
    - name: printing lin lower
      ansible.builtin.debug:
        msg: "{{PVS | lower}}"
    - name: printing the lists
      ansible.builtin.debug:
        msg: '{{list[2] }}'
    - name: Printing dictionaries
      ansible.builtin.debug:
        msg: "{{Dictionary['num1']}}"