- name: demo on varibales(vars)
  hosts: all
  vars:
   PVS: Its a varibale
   list:
    - item1
    - item2
    - item3
    - item4
   Dictionary:
    num1: "1"
    num2: "2"
    num3: "3" 
  vars_files:
   external_vars.yml
  tasks:
    - name: printing the varibale in upper
      ansible.builtin.debug:
        msg: "{{PVS | upper}}"
    - name: printing lin lower
      ansible.builtin.debug:
        msg: "{{PVS | lower}}"
    - name: printing the lists
      ansible.builtin.debug:
        msg: '{{list[2] }}'
    - name: Printing dictionaries
      ansible.builtin.debug:
        msg: "{{Dictionary['num1']}}"
    - name: printing local varibale
      vars: 
        v1: its a local
      ansible.builtin.debug:
        msg: "{{v1}}"
    - name: printing varaibles from externalfiles
      ansible.builtin.debug:
        msg: "{{variable1}}","{{variable1}}"