- name: demo on varibales(vars)
  hosts: all
  vars:
   PVS: Its a varibale
  tasks:
    - name: printing the varibale 
      ansible.builtin.debug:
        msg: "{{PVS | upper}}"
  tasks:
    - name: printing lin lower
      ansible.builtin.debug:
        msg: "{{PVS | lower}}"  